#!/usr/bin/env bash

set -Eeuo pipefail

DEFAULT_DOMAIN="www.mythought.cn"
DEFAULT_PORT="3002"
SITE_NAME="skill-control"

usage() {
  cat <<EOF
用法：
  sudo bash scripts/configure-nginx.sh [域名] [应用端口]

示例：
  sudo bash scripts/configure-nginx.sh
  sudo bash scripts/configure-nginx.sh www.mythought.cn 3002
  sudo bash scripts/configure-nginx.sh skill.mythought.cn 3002

默认域名：${DEFAULT_DOMAIN}
默认端口：${DEFAULT_PORT}
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

DOMAIN="${1:-$DEFAULT_DOMAIN}"
UPSTREAM_PORT="${2:-$DEFAULT_PORT}"

if (( EUID != 0 )); then
  echo "错误：请使用 sudo 运行此脚本。" >&2
  echo "例如：sudo bash scripts/configure-nginx.sh ${DOMAIN} ${UPSTREAM_PORT}" >&2
  exit 1
fi

if [[ ! "$DOMAIN" =~ ^[A-Za-z0-9.-]+$ || "$DOMAIN" != *.* || "$DOMAIN" == .* || "$DOMAIN" == *. ]]; then
  echo "错误：域名格式不正确：${DOMAIN}" >&2
  exit 1
fi

if [[ ! "$UPSTREAM_PORT" =~ ^[0-9]+$ ]]; then
  echo "错误：端口必须是 1 到 65535 之间的整数：${UPSTREAM_PORT}" >&2
  exit 1
fi

UPSTREAM_PORT="$((10#$UPSTREAM_PORT))"
if (( UPSTREAM_PORT < 1 || UPSTREAM_PORT > 65535 )); then
  echo "错误：端口必须是 1 到 65535 之间的整数：${UPSTREAM_PORT}" >&2
  exit 1
fi

install_nginx() {
  if command -v nginx >/dev/null 2>&1; then
    echo "Nginx 已安装，跳过安装。"
    return
  fi

  echo "正在安装 Nginx……"
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y nginx
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y nginx
  elif command -v yum >/dev/null 2>&1; then
    yum install -y nginx
  else
    echo "错误：未找到 apt-get、dnf 或 yum，请先手动安装 Nginx。" >&2
    exit 1
  fi
}

install_nginx

if [[ -d /etc/nginx/sites-available && -d /etc/nginx/sites-enabled ]]; then
  CONFIG_PATH="/etc/nginx/sites-available/${SITE_NAME}"
  ENABLED_PATH="/etc/nginx/sites-enabled/${SITE_NAME}"
else
  mkdir -p /etc/nginx/conf.d
  CONFIG_PATH="/etc/nginx/conf.d/${SITE_NAME}.conf"
  ENABLED_PATH=""
fi

if [[ -f "$CONFIG_PATH" ]] && grep -Eq '^[[:space:]]*listen[[:space:]]+([^;[:space:]]*:)?443([[:space:]]|;)' "$CONFIG_PATH"; then
  echo "错误：${CONFIG_PATH} 已包含 HTTPS（443）配置，为避免覆盖证书设置，脚本已停止。" >&2
  echo "如需修改，请先备份并手动调整现有 Nginx 配置。" >&2
  exit 1
fi

TEMP_CONFIG="$(mktemp)"
trap 'rm -f "$TEMP_CONFIG"' EXIT

cat > "$TEMP_CONFIG" <<EOF
# Generated by Skill Control scripts/configure-nginx.sh
server {
    listen 80;
    listen [::]:80;

    server_name ${DOMAIN};

    client_max_body_size 10m;

    location / {
        proxy_pass http://127.0.0.1:${UPSTREAM_PORT};
        proxy_http_version 1.1;

        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
EOF

BACKUP_PATH=""
CONFIG_EXISTED=false
LINK_EXISTED=false

if [[ -e "$CONFIG_PATH" ]]; then
  CONFIG_EXISTED=true
  if cmp -s "$TEMP_CONFIG" "$CONFIG_PATH"; then
    echo "Nginx 配置已经是最新状态：${CONFIG_PATH}"
  else
    BACKUP_PATH="${CONFIG_PATH}.backup.$(date +%Y%m%d%H%M%S)"
    cp -a "$CONFIG_PATH" "$BACKUP_PATH"
    install -m 0644 "$TEMP_CONFIG" "$CONFIG_PATH"
    echo "已备份旧配置：${BACKUP_PATH}"
  fi
else
  install -m 0644 "$TEMP_CONFIG" "$CONFIG_PATH"
fi

if [[ -n "$ENABLED_PATH" ]]; then
  [[ -e "$ENABLED_PATH" || -L "$ENABLED_PATH" ]] && LINK_EXISTED=true
  ln -sfn "$CONFIG_PATH" "$ENABLED_PATH"
fi

restore_config() {
  if [[ -n "$BACKUP_PATH" && -f "$BACKUP_PATH" ]]; then
    cp -a "$BACKUP_PATH" "$CONFIG_PATH"
  elif [[ "$CONFIG_EXISTED" == false ]]; then
    rm -f "$CONFIG_PATH"
  fi

  if [[ -n "$ENABLED_PATH" && "$LINK_EXISTED" == false ]]; then
    rm -f "$ENABLED_PATH"
  fi
}

if ! nginx -t; then
  echo "Nginx 配置检查失败，正在恢复原配置。" >&2
  restore_config
  nginx -t || true
  exit 1
fi

if command -v systemctl >/dev/null 2>&1; then
  systemctl enable nginx >/dev/null 2>&1 || true
  if systemctl is-active --quiet nginx; then
    systemctl reload nginx
  else
    systemctl start nginx
  fi
else
  nginx -s reload 2>/dev/null || nginx
fi

echo
echo "Nginx 反向代理配置完成："
echo "  http://${DOMAIN}  →  http://127.0.0.1:${UPSTREAM_PORT}"
echo

if command -v curl >/dev/null 2>&1; then
  UPSTREAM_STATUS="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:${UPSTREAM_PORT}/api/health" || true)"
  PROXY_STATUS="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 -H "Host: ${DOMAIN}" http://127.0.0.1/api/health || true)"
  echo "本机检查：应用端口 HTTP ${UPSTREAM_STATUS:-000}，Nginx 代理 HTTP ${PROXY_STATUS:-000}"
  if [[ "$UPSTREAM_STATUS" != "200" || "$PROXY_STATUS" != "200" ]]; then
    echo "提示：如果状态不是 200，请确认 Skill Control 容器正在运行且端口为 ${UPSTREAM_PORT}。"
  fi
fi

echo
echo "接下来请确认："
echo "  1. 阿里云 DNS 的 A 记录已将 ${DOMAIN} 指向本机公网 IP。"
echo "  2. ECS 安全组已开放 TCP 80；配置 HTTPS 后再开放 TCP 443。"
echo "  3. 当前是 HTTP 配置，.env 中应保持 COOKIE_SECURE=false。"
echo "  4. 正式使用账号密码前，请继续为域名配置 HTTPS。"
